image: golang:1.16

stages:
  - test
  - build
  - release

test:
  stage: test
  script:
    - make test
    - make coverage
  only:
    - master

build:
  stage: build
  script:
    - make
    - echo "${CI_JOB_ID}" > CI_JOB_ID.txt # This way you know the job id in the next stage
  artifacts:
    paths:
      - hc*
      - CI_JOB_ID.txt
    expire_in: never
  only:
    - tags

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG --description "Automated release for tag $CI_COMMIT_TAG" \
        --assets-link "{\"name\":\"Download Executable\",\"url\":\"https://git.prolicht.digital/pub/healthcheck/-/jobs/`cat CI_JOB_ID.txt`/artifacts/raw/hc?inline=false\",\"filepath\":\"/binaries/hc\"}" \
        --assets-link "{\"name\":\"Download Checksum\",\"url\":\"https://git.prolicht.digital/pub/healthcheck/-/jobs/`cat CI_JOB_ID.txt`/artifacts/raw/hc.sha256?inline=false\",\"filepath\":\"/binaries/hc.sha256\"}"
  only:
    - tags
